FROM python:3.9

MAINTAINER ckibagendi

WORKDIR /app

# Copy the requirements.txt file to the working directory
COPY requirements.txt .



ENV TZ="Africa/Nairobi"

# Install the Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the application files to the working directory
COPY . .

# Expose the desired port (replace <port> with your desired port number)
EXPOSE 5001

# Run the application
CMD [ "python", "app.py" ]
